export const GET_COVID_STARTED = "GET_COVID_STARTED";
export const GET_COVID_SUCCESSFUL = "GET_COVID_SUCCESSFUL";
export const GET_COVID_FAILED = "GET_COVID_FAILED";
export const GET_COVID_REQUESTED = "GET_COVID_REQUESTED";

